FROM node:10-alpine
WORKDIR '/app'
COPY ./package.json .
RUN npm install
COPY . .

# Env variables
ARG NODE_ENV
ARG ONETEAM_PRODUCTION_DB_SERVER
ARG ONETEAM_PRODUCTION_DB
ARG ONETEAM_PRODUCTION_DB_USERNAME
ARG ONETEAM_PRODUCTION_DB_PASSWORD
ARG ONETEAM_PRODUCTION_JWT_PRIVATE_KEY
ARG ONETEAM_PRODUCTION_SALT
ARG ONETEAM_PRODUCTION_VOLUME
ARG ONETEAM_PRODUCTION_SYSTEM_EMAIL_USERNAME
ARG ONETEAM_PRODUCTION_SYSTEM_EMAIL_PASSWORD
ARG ONETEAM_PRODUCTION_PASSWORD_TOKEN_EXPIRY
ARG ONETEAM_PRODUCTION_MAIL_SERVICE
ARG ONETEAM_PRODUCTION_URL

ENV NODE_ENV ${NODE_ENV}
ENV ONETEAM_PRODUCTION_DB_SERVER ${ONETEAM_PRODUCTION_DB_SERVER}
ENV ONETEAM_PRODUCTION_DB ${ONETEAM_PRODUCTION_DB}
ENV ONETEAM_PRODUCTION_DB_USERNAME ${ONETEAM_PRODUCTION_DB_USERNAME}
ENV ONETEAM_PRODUCTION_DB_PASSWORD ${ONETEAM_PRODUCTION_DB_PASSWORD}
ENV ONETEAM_PRODUCTION_JWT_PRIVATE_KEY ${ONETEAM_PRODUCTION_JWT_PRIVATE_KEY}
ENV ONETEAM_PRODUCTION_SALT ${ONETEAM_PRODUCTION_SALT}
ENV ONETEAM_PRODUCTION_VOLUME ${ONETEAM_PRODUCTION_VOLUME}
ENV ONETEAM_PRODUCTION_SYSTEM_EMAIL_USERNAME ${ONETEAM_PRODUCTION_SYSTEM_EMAIL_USERNAME}
ENV ONETEAM_PRODUCTION_SYSTEM_EMAIL_PASSWORD ${ONETEAM_PRODUCTION_SYSTEM_EMAIL_PASSWORD}
ENV ONETEAM_PRODUCTION_PASSWORD_TOKEN_EXPIRY ${ONETEAM_PRODUCTION_PASSWORD_TOKEN_EXPIRY}
ENV ONETEAM_PRODUCTION_MAIL_SERVICE ${ONETEAM_PRODUCTION_MAIL_SERVICE}
ENV ONETEAM_PRODUCTION_URL ${ONETEAM_PRODUCTION_URL}

CMD ["npm", "start"]